version: '3.1'
services:
  cadastrodb:
    image: mysql:8.0-debian
    container_name: cadastrodb
    environment:
      MYSQL_ROOT_PASSWORD: hibernate
      MYSQL_USER: app_cadastro
      MYSQL_PASSWORD: k4d45tr0
    networks:
      - dados
    volumes:
      #- ./sql/cadastro.sql:/docker-entrypoint-initdb.d/seu_script.sql
      - cadastrodb_vol:/var/lib/mysql
    # ports:
    #   - 3306:3306

  postagemdb:
    image: postgres:16-bookworm
    container_name: postagemdb
    environment:
      POSTGRES_USER: app_postagem
      POSTGRES_PASSWORD: p0st4g3m
    networks:
      - dados
    volumes:
      #- ./sql/postagem.sql:/docker-entrypoint-initdb.d/seu_script.sql
      - postagemdb_vol:/var/lib/postgresql/data

  doasanguepoa:
    image: leogoandete/doasanguepoa-front:latest
    container_name: doasanguepoa_front
    hostname: doasanguepoafront
    networks:
      - backend
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - postagem
      - cadastro
      - login

  postagem:
    image: leogoandete/postagens:latest
    container_name: postagem
    hostname: postagem
    networks:
      - backend
      - monitoramento
      - dados
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postagemdb:5432/postagemdb
      - QUARKUS_DATASOURCE_USERNAME=app_postagem
      - QUARKUS_DATASOURCE_PASSWORD=p0st4g3m
      - QUARKUS_DATASOURCE_KIND=postgresql
      - QUARKUS_DATASOURCE_METRICS_ENABLED=true
      #JAEGER ENV
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317
      #GRAYLOG
      - QUARKUS_LOG_HANDLER_GELF_HOST=graylog
      - QUARKUS_LOG_HANDLER_GELF_PORT=12201
      - PORT=8081
    depends_on:
      - jaeger
      - graylog
      - postagemdb

  cadastro:
    image: leogoandete/cadastro:latest
    container_name: cadastro
    hostname: cadastro
    networks:
      - backend
      - monitoramento
      - dados
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://cadastrodb:3306/cadastrodb
      - QUARKUS_DATASOURCE_USERNAME=app_cadastro
      - QUARKUS_DATASOURCE_PASSWORD=k4d45tr0
      - QUARKUS_DATASOURCE_METRICS_ENABLED=true
      - PORT=8083
      #JAEGER ENV
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317
      #GRAYLOG
      - QUARKUS_LOG_HANDLER_GELF_HOST=graylog
      - QUARKUS_LOG_HANDLER_GELF_PORT=12201
    depends_on:
      - jaeger
      - graylog
      - cadastrodb

  login:
    image: leogoandete/login:latest
    container_name: login
    hostname: login
    networks:
      - backend
      - monitoramento
      - dados
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://cadastrodb:3306/cadastrodb
      - QUARKUS_DATASOURCE_USERNAME=app_cadastro
      - QUARKUS_DATASOURCE_PASSWORD=k4d45tr0
      - QUARKUS_DATASOURCE_METRICS_ENABLED=true
      - PORT=8082
      #JAEGER ENV
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317
      #GRAYLOG
      - QUARKUS_LOG_HANDLER_GELF_HOST=graylog
      - QUARKUS_LOG_HANDLER_GELF_PORT=12201
    depends_on:
      - jaeger
      - graylog
      - cadastrodb
###########
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoramento

  elasticsearch:
    image: elastic/elasticsearch:7.16.3
    # ports:
    #   - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # Use half of the available RAM
      discovery.type: "single-node" # Disable production mode
    networks:
      - monitoramento

  mongo:
    image: mongo:5.0
    networks:
      - monitoramento

  graylog:
    image: graylog/graylog:5.1
    ports:
      - "9000:9000" # HTTP
    #   - "12201:12201/udp" # GELF UDP
    #   - "1514:1514" # GELF TCP
    networks:
      - monitoramento
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "forpasswordencryption"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    depends_on:
      - elasticsearch
      - mongo

  curl:
    image: rapidfort/curl:latest
    command:
      - curl
      - -H
      - "Content-Type: application/json"
      - -H
      - "Authorization: Basic YWRtaW46YWRtaW4="
      - -H
      - "X-Requested-By: curl"
      - -X
      - POST
      - -v
      - -d
      - '{"title":"Application log input", "configuration":{"recv_buffer_size":262144, "bind_address":"0.0.0.0", "port":12201, "decompress_size_limit":8388608}, "type":"org.graylog2.inputs.gelf.udp.GELFUDPInput", "global":true}'
      - http://graylog:9000/api/system/inputs
    networks:
      - monitoramento
    depends_on:
      graylog:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    networks:
      - monitoramento
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    # ports:
    #   - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    networks:
      - monitoramento
    volumes:
      - ./config/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    # ports:
    #   - 3000:3000

networks:
  backend:
    driver: bridge
  monitoramento:
    driver: bridge
  dados:
    driver: bridge

volumes:
  postagemdb_vol:
    driver: local
  cadastrodb_vol:
    driver: local
  prometheus_data:
    driver: local 